#!/command/with-contenv bash
#shellcheck shell=bash

echo "Starting reassembler"

pypy3 -u /opt/iridium-toolkit/reassembler.py -i zmq: -m acars -a json --station $STATION_ID > >(nc -u localhost 5558)
