#!/command/with-contenv bash
#shellcheck shell=bash

echo "Starting mtmap-server"
cd /opt/iridium-toolkit/html2

if [[ -n $LOG_MTMAP ]]; then
    python3 -m http.server --bind 0.0.0.0 8889 2>&1 | stdbuf -o0 awk '{print "[mtmap-server] " strftime("%Y/%m/%d %H:%M:%S", systime()) " " $0}'
else
    python3 -m http.server --bind 0.0.0.0 8889 &> /dev/null
fi
