#!/command/with-contenv bash
#shellcheck shell=bash

if [[ -n ${LOG_ACARS} ]]; then
    socat -u UNIX-CONNECT:/tmp/irdmsock STDOUT | pypy3 -u /opt/iridium-toolkit/reassembler.py -m acars -a json --station $STATION_ID | tee >(nc -4vu localhost 5558)
else
    socat -u UNIX-CONNECT:/tmp/irdmsock STDOUT | pypy3 -u /opt/iridium-toolkit/reassembler.py -m acars -a json --station $STATION_ID > >(nc -4vu localhost 5558)
fi
