#!/command/with-contenv bash
#shellcheck shell=bash

if [[ -n ${LOG_EXTRACTOR_STATS} ]]; then
    iridium-sniffer -i soapy-0 -l --web=8887 --parsed 2> >(stdbuf -o0 awk '{print "[iridium-sniffer] " strftime("%Y/%m/%d %H:%M:%S", systime()) " " $0}') > >(socat -u STDIN UNIX-LISTEN:/tmp/irdmsock,fork)
else
    iridium-sniffer -i soapy-0 -l --web=8887 --parsed 2> >(stdbuf -o0 awk '{print "[iridium-sniffer] " strftime("%Y/%m/%d %H:%M:%S", systime()) " " $0}' | grep WARNING) > >(socat -u STDIN UNIX-LISTEN:/tmp/irdmsock,fork)
fi
