#!/command/with-contenv bash
#shellcheck shell=bash

if [[ -n $LOG_MAP ]]; then
    python3 -m http.server --bind 0.0.0.0 8888 2>&1 | stdbuf -o0 awk '{print "[map-server] " strftime("%Y/%m/%d %H:%M:%S", systime()) " " $0}'
else
    python3 -m http.server --bind 0.0.0.0 8888 &> /dev/null
fi
