#!/command/with-contenv bash
#shellcheck shell=bash

if [[ -n ${DISABLE_EXTRACTOR} ]]; then
    echo "Not starting Extractor as it is disabled in the yml. You should know what you're doing."
    sleep infinity
    exit 0
else
  exec /etc/s6-overlay/scripts/iridium-extractor
fi
