#!/command/with-contenv bash
#shellcheck shell=bash

echo "Starting map reassembler"
cd /opt/iridium-toolkit/html

if [[ -n $LOG_MAP ]]; then
    pypy3 -u /opt/iridium-toolkit/reassembler.py -i zmq: -m live-map 2>&1 | stdbuf -o0 awk '{print "[iridium-reassembler-map] " strftime("%Y/%m/%d %H:%M:%S", systime()) " " $0}'
else
    pypy3 -u /opt/iridium-toolkit/reassembler.py -i zmq: -m live-map &> /dev/null
fi
